# Generated by Django 5.2 on 2025-05-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("Records", "Disques"),
                    ("Clothing", "Vêtements"),
                    ("Posters", "Affiches"),
                    ("Miscellaneous", "Divers"),
                ],
                default="Records",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
