# Generated by Django 5.2 on 2025-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
    ]
