# Generated by Django 5.2 on 2025-05-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_band_like_new_alter_listing_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="like_new",
        ),
    ]
